title: Think
author: ykqin
description: 一蓑烟雨任平生

highlighter: null
permalink: /:title

url: https://ykqin.github.io/
baseurl:

# Custom options:
# color_scheme: azul|ruby|amber|avocado
# color_scheme: avocado
